(function(){
  const $ = (selector, scope=document) => scope.querySelector(selector);
  const $$ = (selector, scope=document) => [...scope.querySelectorAll(selector)];
  const initialMembers = [
    {id:1,name:'Mariana Costa',profession:'Fisioterapeuta',email:'associado@demo.com',city:'Guaxupé',status:'active'},
    {id:2,name:'Lucas Almeida',profession:'Fisioterapeuta',email:'lucas@email.com',city:'Muzambinho',status:'active'},
    {id:3,name:'Ana Ribeiro',profession:'Terapeuta Ocupacional',email:'ana@email.com',city:'Guaxupé',status:'late'},
    {id:4,name:'Paulo Mendes',profession:'Fisioterapeuta',email:'paulo@email.com',city:'Monte Belo',status:'active'},
    {id:5,name:'Camila Nunes',profession:'Estudante',email:'camila@email.com',city:'Guaxupé',status:'pending'}
  ];
  const news = {
    crefito:{category:'Institucional',title:'CREFITO-4 MG e ASSOFIG dialogam sobre fortalecimento regional',body:`<p>O CREFITO-4 MG esteve em Guaxupé, no Sul de Minas, na última semana de setembro, para uma reunião com a Associação de Fisioterapeutas e Terapeutas Ocupacionais de Guaxupé e Região (ASSOFIG).</p><p>Representando o Conselho, o fisioterapeuta Dr. Hugo Goretti, membro da Comissão de Ações Políticas (CAP), ofereceu suporte e orientação técnica aos participantes. Durante o encontro, a diretoria e as comissões da entidade apresentaram um plano de ações e o cronograma de atividades previstas para a região.</p><blockquote>O movimento associativista busca agregar e fortalecer profissionais por região, especialidade e área de atuação.</blockquote><p>A aproximação pode fomentar ações locais, negociações de interesse coletivo, capacitação profissional e benefícios sociais à população.</p>`},
    corrida:{category:'Parceria',title:'ASSOFIG patrocina a 1ª corrida de rua da LIFOT',body:`<p>A ASSOFIG foi patrocinadora oficial do evento realizado pela Liga Acadêmica de Fisioterapia Ortopédica e Traumatológica (LIFOT), do Centro Universitário da Fundação Educacional Guaxupé (UNIFEG).</p><p>A primeira corrida de rua da LIFOT aconteceu em 28 de setembro, em Guaxupé, e também marcou o primeiro encontro de fisioterapeutas e terapeutas ocupacionais da cidade.</p>`},
    retomada:{category:'Associação',title:'Assembleia marca a grande retomada da instituição',body:`<p>No final de setembro de 2025, a ASSOFIG realizou assembleia extraordinária convocada por edital próprio para marcar a grande retomada da instituição.</p><p>Com o objetivo de fortalecer a Fisioterapia e a Terapia Ocupacional em Guaxupé e região, o encontro mobilizou profissionais e estruturou uma nova etapa de atuação da associação.</p>`},
    fundacao:{category:'Nossa história',title:'O encontro que colocou a ASSOFIG no papel',body:`<p>Em 30 de junho de 2017, fisioterapeutas e terapeutas ocupacionais da Baixa Mogiana se reuniram para a leitura e aprovação do estatuto da ASSOFIG.</p><p>O movimento contou com profissionais da região, ex-alunos do UNIFEG e representantes do sistema profissional, unidos pelo desejo de valorizar as categorias e criar uma representação formal.</p><blockquote>O encontro marcou a história da Fisioterapia em Guaxupé e transformou mobilização em uma associação organizada.</blockquote>`}
  };

  function getMembers(){const stored=localStorage.getItem('assofig_members');if(stored)return JSON.parse(stored);localStorage.setItem('assofig_members',JSON.stringify(initialMembers));return [...initialMembers]}
  function saveMembers(items){localStorage.setItem('assofig_members',JSON.stringify(items))}
  function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),3200)}
  function openModal(id){$$('.modal').forEach(m=>m.hidden=true);const modal=$('#'+id);if(!modal)return;modal.hidden=false;document.body.classList.add('modal-open');setTimeout(()=>$('.modal-close',modal)?.focus(),10)}
  function closeModals(){ $$('.modal').forEach(m=>m.hidden=true);document.body.classList.remove('modal-open') }
  function documentDigits(value){return String(value||'').replace(/\D/g,'')}
  function validCPF(value){const d=documentDigits(value);if(d.length!==11||/^(\d)\1{10}$/.test(d))return false;const digit=(base,factor)=>{let sum=0;for(const n of base)sum+=Number(n)*factor--;const rest=(sum*10)%11;return rest===10?0:rest};return digit(d.slice(0,9),10)===Number(d[9])&&digit(d.slice(0,10),11)===Number(d[10])}
  function validCNPJ(value){const d=documentDigits(value);if(d.length!==14||/^(\d)\1{13}$/.test(d))return false;const calc=(base,weights)=>{const sum=[...base].reduce((total,n,i)=>total+Number(n)*weights[i],0);const rest=sum%11;return rest<2?0:11-rest};return calc(d.slice(0,12),[5,4,3,2,9,8,7,6,5,4,3,2])===Number(d[12])&&calc(d.slice(0,13),[6,5,4,3,2,9,8,7,6,5,4,3,2])===Number(d[13])}
  function validDocument(value){const d=documentDigits(value);return d.length===11?validCPF(d):d.length===14?validCNPJ(d):false}
  function formatDocument(value){const d=documentDigits(value).slice(0,14);if(d.length<=11)return d.replace(/^(\d{3})(\d)/,'$1.$2').replace(/^(\d{3})\.(\d{3})(\d)/,'$1.$2.$3').replace(/(\d{3})(\d{1,2})$/,'$1-$2');return d.replace(/^(\d{2})(\d)/,'$1.$2').replace(/^(\d{2})\.(\d{3})(\d)/,'$1.$2.$3').replace(/\.(\d{3})(\d)/,'.$1/$2').replace(/(\d{4})(\d{1,2})$/,'$1-$2')}
  function setAssociationMode(enabled,forceAssociate=false){const field=$('#association-document-field'),input=$('[name=document]',field),subject=$('#contact-form [name=subject]');field.hidden=!enabled;input.required=enabled;if(enabled){if(forceAssociate)subject.value='Quero me associar';setTimeout(()=>input.focus(),550)}else{input.value='';input.setCustomValidity('');input.removeAttribute('aria-invalid')}}

  $$('[data-open]').forEach(button=>button.addEventListener('click',()=>openModal(button.dataset.open)));
  $$('[data-close]').forEach(button=>button.addEventListener('click',closeModals));
  $$('[data-associate]').forEach(link=>link.addEventListener('click',()=>setAssociationMode(true,true)));
  $('#contact-form [name=subject]').addEventListener('change',e=>setAssociationMode(['Quero me associar','Parcerias'].includes(e.target.value)));
  $('#contact-form [name=document]').addEventListener('input',e=>{e.target.value=formatDocument(e.target.value);e.target.setCustomValidity('');e.target.removeAttribute('aria-invalid')});
  $('#contact-form [name=document]').addEventListener('blur',e=>{if(e.target.value&&!validDocument(e.target.value)){e.target.setCustomValidity('Informe um CPF ou CNPJ válido.');e.target.setAttribute('aria-invalid','true')}});
  document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModals()});
  $('.menu-toggle').addEventListener('click',e=>{const nav=$('.main-nav');nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',nav.classList.contains('open'))});
  $$('.main-nav a').forEach(a=>a.addEventListener('click',()=>{$('.main-nav').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false')}));$('.private-link').addEventListener('click',()=>{$('.main-nav').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false')});
    const backToTop=$('.back-to-top'),scrollPortals=[$('#member-portal'),$('#admin-portal')];
  const activeScrollContainer=()=>scrollPortals.find(portal=>!portal.hidden)||null;
  const currentScrollTop=()=>{const portal=activeScrollContainer();return portal?portal.scrollTop:window.scrollY||document.documentElement.scrollTop};
  const updateBackToTop=()=>{const top=currentScrollTop();$('.site-header').classList.toggle('scrolled',top>10);backToTop.classList.toggle('visible',top>350)};
  addEventListener('scroll',updateBackToTop,{passive:true});
  scrollPortals.forEach(portal=>portal.addEventListener('scroll',updateBackToTop,{passive:true}));
  backToTop.addEventListener('click',e=>{e.preventDefault();const portal=activeScrollContainer();if(portal)portal.scrollTo({top:0,behavior:'smooth'});else window.scrollTo({top:0,behavior:'smooth'});setTimeout(updateBackToTop,350)});
  updateBackToTop();
  $('#year').textContent=new Date().getFullYear();

  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&entry.target.classList.add('visible')),{threshold:.12});
  $$('.reveal').forEach(el=>observer.observe(el));

  $$('[data-login-tab]').forEach(tab=>tab.addEventListener('click',()=>{$$('[data-login-tab]').forEach(t=>t.classList.remove('active'));tab.classList.add('active');$('#login-form [name=role]').value=tab.dataset.loginTab;$('#login-title').textContent=tab.dataset.loginTab==='admin'?'Acesso da Diretoria':'Boas-vindas de volta'}));
  $('.toggle-password').addEventListener('click',()=>{const input=$('.password-field input');input.type=input.type==='password'?'text':'password'});
  $('[data-open="forgot-password-modal"]').addEventListener('click',()=>{$('#forgot-password-form [name=email]').value=$('#login-form [name=email]').value.trim()});
  $('#forgot-password-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=$('button[type=submit]',form),data=Object.fromEntries(new FormData(form));button.disabled=true;button.textContent='Enviando...';try{await AssofigAPI.forgotPassword(data);form.reset();closeModals();toast('Se o e-mail estiver cadastrado, enviaremos as instruções de recuperação.')}catch(err){toast(err.message)}finally{button.disabled=false;button.innerHTML='Enviar instruções <span>→</span>'}});

  $('#login-form').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const button=$('button[type=submit]',e.currentTarget);button.disabled=true;button.textContent='Entrando...';try{const result=await AssofigAPI.login(data);localStorage.setItem('assofig_token',result.token);closeModals();showPortal(data.role)}catch(err){toast(err.message)}finally{button.disabled=false;button.innerHTML='Entrar na área privativa <span>→</span>'}});
  $('#signup-form').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));try{await AssofigAPI.submitApplication(data);e.currentTarget.reset();closeModals();toast('Solicitação recebida! A diretoria entrará em contato.')}catch(err){toast(err.message)}});
  $('#contact-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,data=Object.fromEntries(new FormData(form)),association=data.subject==='Quero me associar',needsDocument=association||data.subject==='Parcerias',documentInput=form.elements.document;if(needsDocument){if(!validDocument(data.document)){documentInput.setCustomValidity('Informe um CPF ou CNPJ válido.');documentInput.setAttribute('aria-invalid','true');documentInput.reportValidity();return}data.document=documentDigits(data.document)}else delete data.document;try{if(association){await AssofigAPI.submitApplication(data);toast('Solicitação recebida! A diretoria entrará em contato.')}else{await AssofigAPI.sendContact(data);toast('Mensagem enviada com sucesso!')}form.reset();setAssociationMode(false)}catch(err){toast(err.message)}});
  $$('.news-card').forEach(card=>card.addEventListener('click',e=>{if(e.target.closest('button')||e.currentTarget===card){const item=news[card.dataset.news];$('#news-modal-category').textContent=item.category;$('#news-modal-title').textContent=item.title;$('#news-modal-body').innerHTML=item.body;openModal('news-modal')}}));

  function portalLayout(role,content){const isAdmin=role==='admin';return `<div class="portal-shell"><aside class="portal-sidebar"><div class="portal-logo"><img src="img/assofig.jpg" alt=""><strong>ASSOFIG<small>${isAdmin?'Painel da diretoria':'Portal do associado'}</small></strong></div><div class="portal-user"><div class="avatar">${isAdmin?'DA':'MC'}</div><div><strong>${isAdmin?'Diretoria ASSOFIG':'Mariana Costa'}</strong><small>${isAdmin?'Administrador':'Fisioterapeuta'}</small></div></div><nav class="portal-nav"><button class="active">▦ Visão geral</button><button>${isAdmin?'♙ Associados':'♙ Meu cadastro'}</button><button>${isAdmin?'$ Financeiro':'$ Pagamentos'}</button><button>${isAdmin?'◉ Notícias e eventos':'✦ Benefícios'}</button></nav><button class="portal-logout" type="button">← Sair da área privativa</button></aside><main class="portal-main">${content}</main></div>`}

  function memberContent(){const member=getMembers().find(m=>m.email==='associado@demo.com')||initialMembers[0];const late=member.status==='late';return `<header class="portal-top"><div><h1>Olá, Mariana 👋</h1><p>Acompanhe seu cadastro, contribuições e benefícios.</p></div><span class="status-pill ${late?'late':'active'}">${late?'Contribuição em atraso':'Associada em dia'}</span></header>${late?`<div class="panel" style="border-left:4px solid var(--danger);margin-bottom:18px"><strong style="color:var(--danger)">Existe uma pendência financeira em seu cadastro.</strong><p style="margin:4px 0 0;color:var(--muted)">Regularize a contribuição ou entre em contato com a tesouraria.</p></div>`:''}<div class="portal-grid"><section class="panel"><h2>Meus dados</h2><div class="profile-data"><div><small>Nome</small><strong>Mariana Costa</strong></div><div><small>Profissão</small><strong>Fisioterapeuta</strong></div><div><small>Registro</small><strong>CREFITO-4 000000-F</strong></div><div><small>Cidade</small><strong>Guaxupé - MG</strong></div><div><small>E-mail</small><strong>associado@demo.com</strong></div><div><small>Telefone</small><strong>(35) 99999-0000</strong></div></div><button class="read-more" type="button" data-profile-edit>Solicitar alteração cadastral →</button></section><section class="payment-card"><small>Próxima contribuição</small><strong>R$ 50,00</strong><span>Vencimento: 10/08/2026</span><div class="payment-actions"><button type="button" data-payment="pix">Pagar com PIX</button><button type="button" data-payment="card">Cartão</button></div></section></div><div class="portal-grid"><section class="panel"><h2>Histórico de benefícios</h2><div class="history-list"><div class="history-item"><span>✦</span><div><strong>Workshop de Terapia Manual</strong><small>Inscrição com desconto • 18/06/2026</small></div></div><div class="history-item"><span>◎</span><div><strong>Encontro Regional ASSOFIG</strong><small>Participação gratuita • 22/05/2026</small></div></div><div class="history-item"><span>⌁</span><div><strong>Convênio parceiro</strong><small>Benefício utilizado • 04/04/2026</small></div></div></div></section><section class="panel"><h2>Documentos e atalhos</h2><div class="history-list"><a class="history-item" href="docs/Estatuto ASSOFIG_registrado.pdf" download><span>↓</span><div><strong>Estatuto ASSOFIG</strong><small>Baixar PDF</small></div></a><a class="history-item" href="mailto:contato@assofig.com"><span>✉</span><div><strong>Falar com a associação</strong><small>Enviar e-mail</small></div></a></div></section></div>`}

  function adminContent(){const members=getMembers(),active=members.filter(m=>m.status==='active').length,late=members.filter(m=>m.status==='late').length,pending=members.filter(m=>m.status==='pending').length;return `<header class="portal-top"><div><h1>Painel administrativo</h1><p>Gestão de associados e situação financeira.</p></div><span class="status-pill active">Gestão 2026–2028</span></header><div class="metric-grid"><div class="metric"><small>Total de cadastros</small><strong class="blue">${members.length}</strong></div><div class="metric"><small>Sócios ativos</small><strong class="green">${active}</strong></div><div class="metric"><small>Inadimplentes</small><strong class="red">${late}</strong></div><div class="metric"><small>Aguardando análise</small><strong>${pending}</strong></div></div><section class="panel" style="margin-top:18px"><div class="admin-tools"><input id="member-search" placeholder="Buscar por nome, profissão ou cidade"><button class="btn btn-blue" type="button" data-add-member>+ Novo associado</button></div><div class="portal-table-wrap"><table class="portal-table"><thead><tr><th>Associado</th><th>Profissão</th><th>Cidade</th><th>Situação</th><th>Ações</th></tr></thead><tbody>${members.map(memberRow).join('')}</tbody></table></div></section>`}
  function memberRow(m){const label={active:'Em dia',late:'Inadimplente',pending:'Pendente'}[m.status];return `<tr data-member-row="${m.id}"><td><strong>${m.name}</strong><br><small>${m.email}</small></td><td>${m.profession}</td><td>${m.city}</td><td><span class="status-pill ${m.status==='active'?'active':m.status==='late'?'late':''}">${label}</span></td><td><div class="table-actions"><button data-edit-member="${m.id}">Editar</button><button data-toggle-member="${m.id}">${m.status==='late'?'Regularizar':'Inadimplência'}</button><button data-delete-member="${m.id}">Excluir</button></div></td></tr>`}

  function showPortal(role){const portal=role==='admin'?$('#admin-portal'):$('#member-portal');portal.innerHTML=portalLayout(role,role==='admin'?adminContent():memberContent());portal.hidden=false;document.body.classList.add('modal-open');$('.portal-logout',portal).addEventListener('click',()=>{portal.hidden=true;document.body.classList.remove('modal-open');localStorage.removeItem('assofig_token')});if(role==='member')bindMember(portal);else bindAdmin(portal)}
  function bindMember(portal){$$('[data-payment]',portal).forEach(b=>b.addEventListener('click',()=>openPayment(b.dataset.payment)));$('[data-profile-edit]',portal).addEventListener('click',()=>toast('Solicitação enviada à secretaria para conferência.'))}
  function openPayment(type){const modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="modal-backdrop"></div><div class="modal-panel"><button class="modal-close" type="button">×</button><span class="eyebrow">Pagamento</span><h2>${type==='pix'?'Pague com PIX':'Pagamento com cartão'}</h2><div class="payment-dialog">${type==='pix'?`<div class="pix-box"><small>Chave PIX demonstrativa</small><div class="pix-key">contato@assofig.com</div></div><button class="btn btn-blue" type="button" data-copy-pix>Copiar chave PIX</button>`:`<label>Número do cartão<input placeholder="0000 0000 0000 0000"></label><div class="form-row"><label>Validade<input placeholder="MM/AA"></label><label>CVV<input placeholder="000"></label></div><button class="btn btn-blue" type="button" data-confirm-card>Continuar pagamento</button>`}</div></div>`;document.body.appendChild(modal);$('.modal-close',modal).onclick=()=>modal.remove();$('.modal-backdrop',modal).onclick=()=>modal.remove();$('[data-copy-pix]',modal)?.addEventListener('click',()=>{navigator.clipboard?.writeText('contato@assofig.com');toast('Chave PIX copiada.')});$('[data-confirm-card]',modal)?.addEventListener('click',()=>{modal.remove();toast('Pagamento demonstrativo iniciado.')})}

  function bindAdmin(portal){$('#member-search',portal).addEventListener('input',e=>{$$('tbody tr',portal).forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(e.target.value.toLowerCase()))});$('[data-add-member]',portal).addEventListener('click',()=>memberEditor());$$('[data-edit-member]',portal).forEach(b=>b.addEventListener('click',()=>memberEditor(+b.dataset.editMember)));$$('[data-toggle-member]',portal).forEach(b=>b.addEventListener('click',()=>{const members=getMembers(),item=members.find(m=>m.id===+b.dataset.toggleMember);item.status=item.status==='late'?'active':'late';saveMembers(members);refreshAdmin();toast(item.status==='late'?'Inadimplência registrada e visível ao associado.':'Situação financeira regularizada.')}));$$('[data-delete-member]',portal).forEach(b=>b.addEventListener('click',()=>{if(confirm('Excluir este cadastro?')){saveMembers(getMembers().filter(m=>m.id!==+b.dataset.deleteMember));refreshAdmin();toast('Cadastro excluído.')}}))}
  function refreshAdmin(){const portal=$('#admin-portal');portal.innerHTML=portalLayout('admin',adminContent());$('.portal-logout',portal).addEventListener('click',()=>{portal.hidden=true;document.body.classList.remove('modal-open')});bindAdmin(portal)}
  function memberEditor(id){const current=id?getMembers().find(m=>m.id===id):{name:'',profession:'Fisioterapeuta',email:'',city:'Guaxupé',status:'active'};const modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="modal-backdrop"></div><div class="modal-panel"><button class="modal-close" type="button">×</button><span class="eyebrow">Cadastro</span><h2>${id?'Alterar associado':'Novo associado'}</h2><form id="member-editor"><label>Nome completo<input name="name" required value="${current.name}"></label><div class="form-row"><label>Profissão<select name="profession"><option ${current.profession==='Fisioterapeuta'?'selected':''}>Fisioterapeuta</option><option ${current.profession==='Terapeuta Ocupacional'?'selected':''}>Terapeuta Ocupacional</option><option ${current.profession==='Estudante'?'selected':''}>Estudante</option></select></label><label>Cidade<input name="city" required value="${current.city}"></label></div><label>E-mail<input type="email" name="email" required value="${current.email}"></label><label>Situação<select name="status"><option value="active" ${current.status==='active'?'selected':''}>Em dia</option><option value="late" ${current.status==='late'?'selected':''}>Inadimplente</option><option value="pending" ${current.status==='pending'?'selected':''}>Pendente</option></select></label><button class="btn btn-blue" type="submit">Salvar cadastro</button></form></div>`;document.body.appendChild(modal);$('.modal-close',modal).onclick=()=>modal.remove();$('.modal-backdrop',modal).onclick=()=>modal.remove();$('#member-editor',modal).onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget)),members=getMembers();if(id){const index=members.findIndex(m=>m.id===id);members[index]={...members[index],...data};await AssofigAPI.updateMember(id,data)}else{const item={id:Date.now(),...data};members.push(item);await AssofigAPI.createMember(item)}saveMembers(members);modal.remove();refreshAdmin();toast('Cadastro salvo com sucesso.')}}
})();
